### ISSUE TITLE
Error: HTTP error! status: 403

### ISSUE THREAD

**Issue by enzo-ship-it** [ewkt/Vinted-API-Discord-Scraper-Bot#1]
Salut, 
J'ai cette erreur quand j'exécute le code, saurais-tu me dépanner ? 

Error during fetch: Error: HTTP error! status: 403
    at file:///Users/xx/Downloads/Vinted-API-Discord-Scraper-Bot-main/src/api/search.js:31:15
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    
 Merci !

**Comment by ewkt** [comment]
hello! l'erreur 403 c'est un pb d'authentification donc probablement que le cookie est invalide. si tu as le temps envoie moi un message sur discord qu'on puisse debug ensemble!

usr: thewwk

**Comment by CleJ007** [comment]
Salut, j'ai le même problème. Le bot tourne une trentaine de secondes en fonctionnant parfaitement puis apres il y a ce message d'erreur.

**Comment by ewkt** [comment]
> Salut, j'ai le même problème. Le bot tourne une trentaine de secondes en fonctionnant parfaitement puis apres il y a ce message d'erreur. Merci !

Hello, pour @enzo-ship-it on pense que c'était lié au fait qu'il était sous macos (erreur 403 immediatement) le code marche bien sous windows

Si ton code tourne bien pendant 30sec tu peux essayer de voir si le probleme n'est pas juste une rate-limit, comme j'ai pas implémenté de proxy rotatif tu te heurte peut-être au maximum. 

Tu as combien de requetes en parallele et c'est quoi ton delai de rafraichissement?

D'experience j'ai l'impression que ça bloque autour de 60-100 req/min

**Comment by nexaltt** [comment]
Hello , Ton projet est super intéressant et je me suis permit de le récuperer et de le tester. J'aimerais savoir , comme tu peux le voir sur le screen j'ai rajouter combien de temps le post a été posté 
[
![Capture d'écran 2024-04-25 115030](https://github.com/ewkt/Vinted-API-Discord-Scraper-Bot/assets/82239261/7791833d-45d4-45cb-a3b6-903255d82967)
](url)


Comme tu peux le voir les articles récupérer sont uniquement ce qui sont posté il y'a 30 secondes environ mais pas ce qui sont posté directement. 

as tu une solution pour qu'il récuperer uniquement les nouveaux article posté ? pas se deja présent sur la page

**Comment by ewkt** [comment]
Hello, merci pour ton commentaire je suis content que le code marche pour toi. La question des délais est très débatue dans le milieu.

En utilisant la requete par api comme dans mon projet le seul facteur d'ameilloration ça va etre la fréquence des requetes. Si tu ne dépasse pas la barre de 1req/seconde tu n'auras pas de soucis et ça va probablement réduire de manière générale les délais. Au dessus tu vas devoir utiliser des proxy rotatifs pour bypass la rate-limit.

En ce qui concerne les délais super variables entre chaque article, c'est parceque vinted procède à une vérification de chaque article qui peut durer + ou - longtemps. Le délai indiqué sur le post est calculé avec le timestamp de la photo qui est l'heure a laquelle l'article a été uploadé ≠ l'heure a laquelle il est publié sur l'api.

Pour te rassurer tu auras toujours les résultats de la recherche par api avant la recherche normale.

Il n'y a malheureusement pas de manière de calculer le délais entre le post du bot et entre la disponibilité de l'article via l'api du catalogue.

En gros si tu fais des requetes assez frequentes tu n'auras jamais de délais, l'indication sur le post discord indique combien de temps ça a pris a vinted pour valider l'article.

J'espere avoir repondu à ta question.

THEO EWBANK

ING2 - GMA
________________________________

**Comment by nexaltt** [comment]
Donc tu pense que avec plusieurs requete par seconde on pourrait arriver à avoir un bot qui fonctionnerai sans délai ? 

![Capture d'écran 2024-04-25 122445](https://github.com/ewkt/Vinted-API-Discord-Scraper-Bot/assets/82239261/4d4bba2f-533d-43d2-a973-c18a182d11fb)

Comme par exemple sur ce serveur le bot récupere des articles sans délai

**Comment by ewkt** [comment]
Sur exactement la même recherche en ce moment entre ton bot et celui du serveur tu constate combien de délais entre la publication d'un même article?

Pour répondre à ta question, oui, parceque le fonctionnement du bot que j'ai programmé est aussi 0-délais! Sur le serveur le timestamp "il y a 1seconde" c'est juste l'heure a laquelle le message a été envoyé à discord donc tu as des delais tres courts 0-5secondes

**Comment by nexaltt** [comment]
Sur l'image que j'ai publié le " il y'a 1 seconde " c'est justement le timestamp de la photo qui est l'heure a laquelle l'article a été uploadé et non l'heure a laquelle le message a été envoyé à discord. 

![image](https://github.com/ewkt/Vinted-API-Discord-Scraper-Bot/assets/82239261/f6ce273b-f22c-40fa-a783-a16a79cf3fbc)µ
![image](https://github.com/ewkt/Vinted-API-Discord-Scraper-Bot/assets/82239261/ebe1ea8e-370b-463b-b369-00b9cbc02d14)

**Comment by ewkt** [comment]
Je t'invite a comparer la même recherche entre les deux bots discord en live pour voir les delais. Si tu n'as pas dev l'autre bot (ou acces a son code) tu ne peux pas savoir comment le timestamp a été calculé.

N'hésite pas à poster la comparaison cote à cote dans ce thread (ou tu peux m'envoyer un dm sur discord)

THEO EWBANK

ING2 - GMA
________________________________

**Comment by nexaltt** [comment]
Pas access aux codes je vais faire mes recherches et je reviendrais vers toi 

Merci à toi

**Comment by ewkt** [comment]
Ajout d'un proxy rotatif pour déjouer la rate-limit
