### ISSUE TITLE
Auto buy

### ISSUE THREAD

**Issue by turpez** [ewkt/Vinted-API-Discord-Scraper-Bot#2]
Bonjour, je cherche depuis un moment et je n'arrive pas à récupérer ses informations :

configuration: il faut récupérer des infos en capturant le trafic lors d'un login sur vinted.fr

trouver 'access_token' et 'refresh_token' dans le "POST" à 'https://www.vinted.fr/oauth/token'.
trouver le cookie 'X-CSRF-Token' dans les headers d'une requete comme 'checkout'.

**Comment by ewkt** [comment]
salut! 
mes explications sont peut-etre pas assez claires désolé, j'ai vu ce tuto si tu veux essayer de le suivre. N'hésite pas si tu as d'autres problèmes!

![image](https://github.com/ewkt/Vinted-API-Discord-Scraper-Bot/assets/117741458/7a636c56-6642-4305-8846-bae48dc96b14)

**Comment by turpez** [comment]
Sa doit être moi aussi qui comprends mal je vais essayé sa et j'aimerais bien t'aider pour ton code si tu veux bien, bien sur :)

**Comment by turpez** [comment]
Ce tuto et pas exacte, mais j'ai réussi merci je l'ai lancé mets la j'attends que cela envoi des annonces, je verrais bien si cela fonctionne mets ses bizarres que je n'ai rien j'ai laissé tes filtres par défaut

**Comment by ewkt** [comment]
thewwk sur discord si tu veux qu'on check ça ensemble

**Comment by turpez** [comment]
Je t'es demandé en amis et pour l'instant j'ai pas de notification

**Comment by dewittethomas** [comment]
> salut! mes explications sont peut-etre pas assez claires désolé, j'ai vu ce tuto si tu veux essayer de le suivre. N'hésite pas si tu as d'autres problèmes!
> 
> ![image](https://private-user-images.githubusercontent.com/117741458/337370447-7a636c56-6642-4305-8846-bae48dc96b14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMDgyOTUsIm5iZiI6MTcxODIwNzk5NSwicGF0aCI6Ii8xMTc3NDE0NTgvMzM3MzcwNDQ3LTdhNjM2YzU2LTY2NDItNDMwNS04ODQ2LWJhZTQ4ZGM5NmIxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQxNTU5NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjIwYTMzZjFhMzI2YTdjZGQ5MDhjYmUwYWFlZTZiMjExYWIzNzk3NTUxYjNhM2NhYjEwMTYxY2NiYjk1YzIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nOrHW3MQ_Te2Xz3-OIoRqm-ao8eFOy2lXaASR3mMcOw)

Tu l'as d'ou le tuto svp? Merci!

**Comment by ewkt** [comment]
tutorial in the thread for people having issues finding the cookies
